name: CI/CD
on: [push]
env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_RESERVASA }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_RESERVASA }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_RESERVASA }}

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/reservas-a' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/reservas-a' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      - name: pull Vercel Environtment Variables
        run: vercel pull --yes --token=${{ env.VERCEL_TOKEN_RESERVASA }}
      - name: Trigger Vercel Deployment
        run: vercel deploy --no-wait --token=${{ env.VERCEL_TOKEN_RESERVASA }}

