# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["BusquedaDeVuelosB"]
  pull_request:
    branches: ["BusquedaDeVuelosB"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Intall dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          overwrite: true

  build:
    runs-on: ubuntu-latest
    # needs: test # This job depends on the test job

    env:
      BUILD_DIR: build

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: ${{ env.BUILD_DIR }}
          overwrite: true
