# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["BusquedaDeVuelosB"]
  pull_request:
    branches: ["BusquedaDeVuelosB"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: ${{ env.BUILD_DIR }}
          overwrite: true

  test:
    runs-on: ubuntu-latest
    needs: build # This job depends on the build job

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Intall dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          overwrite: true
          
  sonarcloud:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Intall dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
