name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_JezcVfCZRerIzOEwWtEpLAq0
  VERCEL_PROJECT_ID: prj_3hWIPLzrfZyB0vAts2dAEMX6ieAb
on:
  push:
    branches: [pagosA]
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=SJPGjQGBQevuberF1wuDQjl8
      - name: Build Project Artifacts
        run: vercel build --token=SJPGjQGBQevuberF1wuDQjl8
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=SJPGjQGBQevuberF1wuDQjl8